spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.jrlajtw.mongodb.net/?retryWrites=true&w=majority
      database: budgetbuddy

rates:
  url: https://api.exchangeratesapi.io

